### PR TITLE
Random Deadlock fix

### PR DESCRIPTION
**Pull request by JPery**
Hi.

First of all, thank you for this project which helped me a lot with some logging issues.

As mentioned in #26, it randomly causes a Deadlock in my program. This issue is bigger as the number of processes grow. As also commented in the issue, this is a common issue but it should be fixed in Python >=3.7 as mentioned in https://codewithoutrules.com/2017/08/16/concurrency-python/.

Also, in the [docs](https://docs.python.org/3/library/queue.html#simplequeue-objects) of the SimpleQueue class it says: "a put() or get() call can be interrupted by another put() call in the same thread without deadlocking or corrupting internal state inside the queue".

I've made this pull request in order to fix the issue and maintain compatibility with Python 2 (knowing that the issue will stay)

Best regards,
Jorge

### CODE REVIEW

**Comment by jruere** [comment]
I am so sorry for the delay. I'll review this weekend.

**Comment by jruere** [comment]
AFAIU this PR switches from `multiprocessing.Queue` to `multiprocessing.SimpleQueue` only.

This could help the locking problem as `SimpleQueue` does not use an internal buffer plus a thread but instead blocks until the log record is pushed to a pipe.

Regarding the article, it references a new queue which fixes this problem in Python 3.7 but that queue is `queue.SimpleQueue`, not `multiprocessing.SimpleQueue` which exists at least since Python 2.7. It may help with the problem anyway, it's just not mentioned in the article.

Later there's a quote from the docs about `SimpleQueue` being reentrant. This is again about `queue.SimpleQueue`, which is not used. `multiprocessing.SimpleQueue` is not reentrant AFAICS: https://github.com/python/cpython/blob/27fc3b6f3fc49a36d3f962caac5c5495696d12ed/Lib/multiprocessing/queues.py#L341

OK, so is there any disadvantage to using `SimpleQueue` rather than `Queue`? I see a few:

1. Logging is now a blocking operation which requires the main thread to keep up or children will be slowed down. I really dislike this. I prefer the previous behaviour of buffering and *dropping log records if the main proc cannot keep up*. I realize this is a matter of taste. Dropping records is never done by `logging` and most users will be unaware.
1. There is a condition in the receiver which was removed. The except of `Empty` will never happen now. This leads to a short hang. I don't have a test for this, apologies. The commit which fixed this is: 9f73be6ceb528d7fac13234356b46660193dedb3

What do you think?

Are you using this in production? Did you notice any slow down?

**Comment by JPery** [comment]
Hi. In first place I want to apologize my delay in answering this topic. I'll try to answer all of the topics.

I've tried using `queue.SimpleQueue` instead of `multiprocessing.SimpleQueue` but it seems like `queue.SimpleQueue` doesn't likes threads as all the test failed because the log messages are not receiving. For this reason is why I used `multiprocessing.SimpleQueue`.

As you say, logging is now a blocking operation but it is also a blocking operation on `logging`, so I don't see any inconvenience here. This is also a safer approach IMHO. Also I think that dropping records could be very inconvenient in some cases (f.e you want to debug some application).

As you also comment, the except of Empty will never happen now. The hang could be removed by changing the timeout in `self._receive_thread.join(5.0)` to, f.e, `0.1`. 

I'm using the changes in production and I didn't see any slow downs and it seems like the deadlock problem is solved. Also we can try to write some test in order to test cases when there are much logging load in order to see if the performance decays.

I hope this helps.

Best regards,
Jorge

**Comment by jruere** [comment]
Hi Jorge,
I'm very sorry for the delay!

> I've tried using `queue.SimpleQueue` instead of `multiprocessing.SimpleQueue` but it seems like `queue.SimpleQueue` doesn't likes threads as all the test failed because the log messages are not receiving. For this reason is why I used `multiprocessing.SimpleQueue`.

The `queue` package is for threading but this library is useless for threading, it's only useful when using multiple processes.

Are you using threads or processes?

> As you say, logging is now a blocking operation but it is also a blocking operation on `logging`, so I don't see any inconvenience here. This is also a safer approach IMHO. Also I think that dropping records could be very inconvenient in some cases (f.e you want to debug some application).

This is a design choice. It's fine for me either way, as long as it's clear, but I'm reluctant to change it without a very compelling reason as people are now expecting the current behaviour.

Fixing this problem would be a very compelling reason.

> As you also comment, the except of Empty will never happen now. The hang could be removed by changing the timeout in `self._receive_thread.join(5.0)` to, f.e, `0.1`.

Yes, but that timeout also has a reason: it allows child processes to flush all records.
By reducing the timeout we are narrowing the margin to get all records. Bear in mind that this was an actual problem with someone opening an [actual ticket](https://github.com/jruere/multiprocessing-logging/issues/18).

> I'm using the changes in production and I didn't see any slow downs and it seems like the deadlock problem is solved. Also we can try to write some test in order to test cases when there are much logging load in order to see if the performance decays.

This would be great irrespective of this PR!

I'll think some more about the pros and cons of this implementation.

**Pull request closed without merging**
