### PR TITLE
Fix OSError infinite loop in new python versions

### PR DESCRIPTION
**Pull request by bloomen**

### CODE REVIEW

**Comment by jruere** [comment]
@bloomen I don't like that it renames an exception.

Apparently we should catch OSError instead of BrokenPipeException. I believe that should work on all versions but I have not tested it.

Also, is there a way to add a regression test for this problem?

**Comment by bloomen** [comment]
@jruere Yea good point, I added an explicit catch of OSError instead.

The easiest way to reproduce the problem is running the minimal example from https://github.com/jruere/multiprocessing-logging/issues/56#issuecomment-1156473221 but I am not sure how I'd add a test for this as part of the unit test suite. The infinite logging loop happens on exit.

**Comment by bloomen** [comment]
@jruere How do we move this forward? Btw, congrats on winning the cup :D

**Comment by AlexLinus** [comment]
@jruere Hi. Can we move it forward somehow? Seems many people waiting for?

**Review by jruere — APPROVED** [review]

**Comment by jruere** [comment]
Thank you, @bloomen !

**Comment by jruere** [comment]
I'll release a new version this week.

**Pull request merged**
